### ISSUE TITLE
Make API /version endpoint keys all lowercase

### ISSUE THREAD

**Issue by tjmills-dev** [lennycolton/VFPC#121]
All keys on /version should be lowercase - i.e.

- API_Version -> api_version
- Min_Version -> min_version
- VFPC_Version -> vfpc_version

This was what resulted in some VFPC errors at about 2200 on 17/09/21

Links to https://github.com/VFPC/UKVFPCAPI/issues/35

**Comment by lennycolton** [comment]
@GeekPro101 Any chance you could offer both formats on the API for the time being? Makes it easier for me to implement the alterations.

**Comment by tjmills-dev** [comment]
Can do @lennycolton - see https://github.com/VFPC/UKVFPCAPI/commit/7293bd7c1215c6ced99d1b9d020bda657f4e70f3

**Comment by lennycolton** [comment]
> Can do @lennycolton - see https://github.com/VFPC/UKVFPCAPI/commit/7293bd7c1215c6ced99d1b9d020bda657f4e70f3

Excellent ta
