### ISSUE TITLE
Failed DTG update from API

### ISSUE THREAD

**Issue by scotflieger** [lennycolton/VFPC#149]
With ES 3.2.34 with latest UK Controller Pack I repeatedly get the error messages:

System: Failed to read date/last update record from API 
System: Failed to read day/time from API.

**Comment by lennycolton** [comment]
Fixed in v3.7.0 trunk branch. Hotfix to be pushed for v3.6.x stream.

**Comment by lennycolton** [comment]
Fixed in v3.6.4
