### ISSUE TITLE
"Failed to read date / last update record from API" reported with version 3.6.4

### ISSUE THREAD

**Issue by ghost** [lennycolton/VFPC#159]
From VATSIM UK DIscord ...

Chris Butterworth — Today at 17:12
Having probs with the VFPC plug-in. Getting a failure message “failed to read date/last update record from API”
Have unloaded / reloaded and reinstalled the plugin but no joy. ? Any advice please 🙏
Ray Benitez — Today at 17:44
Which version number are you using, Chris?
Latest is 3.6.4 and that bug should have been fixed.
Chris Butterworth — Today at 17:45
3.6.4

**Comment by oldenough** [comment]
Talked to the other fellow who reported the problem yesterday.  He has updated 🪟 since then and isn't getting the problem any more, but will send a screenshot if he sees it again.

**Comment by flyingscotsman59** [comment]
Can we close this issue?

**Comment by oldenough** [comment]
Ok with me; we can reopen later if we need to. What should we try to get from the next person to report the problem?
